---
title: Emangelist
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: page
    image_path: 
    categorysubtitle: 
    title: 
    subtitle: 
    date: 
    author: Michael Sheerin
