defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
      image_path:
      categorysubtitle:
      title:
      subtitle:
      date:
      author: Michael Sheerin
---
title: Emangelist
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
kramdown:
  hard_wrap: true
